### ISSUE TITLE
Running ssdm git * commands errors

### ISSUE THREAD

**Issue by srang** [gjbianco/ssdm#2]
When running `ssdm git <command>` I'm getting errors such as:

``` bash
> ssdm git add .cmus/playlist.pl .cmus/lib.pl
git: 'add,.cmus/playlist.pl,.cmus/lib.pl' is not a git command. See 'git --help'.
Error: 'git add,.cmus/playlist.pl,.cmus/lib.pl' failed
```

It looks like this has to do with how arguments passed to ssdm are spliced and joined when passed to git

**Comment by gjbianco** [comment]
Fixed in v0.1.3
